/* GENERATED by tools/color/emit.mjs. Do not hand-edit.
 *
 * Change a colour in tools/color/palette.mjs or semantic.mjs, run `pnpm tokens:build`, and
 * commit the result. `pnpm tokens:check` fails CI if these files are stale, and
 * `pnpm color:contrast` fails it if any pair drops below its WCAG threshold.
 */

/**
 * Palette primitives. Exported for tooling and tests — NOT for components, which must use the
 * semantic CSS variables so a theme change reaches them.
 */
export const palette = {
  teal: {
    50: '#f2fdfc',
    100: '#e1f8f7',
    200: '#c3efee',
    300: '#99e1df',
    400: '#5ec4c2',
    500: '#13a3a2',
    600: '#008180',
    700: '#006a69',
    800: '#005454',
    900: '#004242',
    950: '#002626',
  },
  slate: {
    50: '#f8fafc',
    100: '#eff3f6',
    200: '#dee6ec',
    300: '#c6d4dc',
    400: '#a2b4be',
    500: '#7e929d',
    600: '#61737e',
    700: '#4a5f6b',
    800: '#354c59',
    900: '#243c49',
    950: '#10232d',
  },
  green: {
    50: '#f4fdf6',
    100: '#e5f9e9',
    200: '#cbf0d3',
    300: '#a6e2b5',
    400: '#75c68c',
    500: '#44a565',
    600: '#218548',
    700: '#146e39',
    800: '#0b582c',
    900: '#084522',
    950: '#022811',
  },
  amber: {
    50: '#fff9f2',
    100: '#fff0dd',
    200: '#fee0b9',
    300: '#f7c88a',
    400: '#e1a44a',
    500: '#bf8000',
    600: '#976400',
    700: '#7d5200',
    800: '#644000',
    900: '#4f3200',
    950: '#2f1c00',
  },
  red: {
    50: '#fff8f7',
    100: '#ffeeec',
    200: '#ffdbd7',
    300: '#ffbfb7',
    400: '#ff8a7e',
    500: '#e35e54',
    600: '#bd3e37',
    700: '#9e2f2a',
    800: '#80231f',
    900: '#651b17',
    950: '#3d0c0a',
  },
  blue: {
    50: '#f7faff',
    100: '#ebf3ff',
    200: '#d6e6ff',
    300: '#b6d3ff',
    400: '#7eb2ff',
    500: '#558ee4',
    600: '#386fc0',
    700: '#2a5ba1',
    800: '#1f4882',
    900: '#183867',
    950: '#0a203f',
  },
} as const

export type ColorFamily = keyof typeof palette
export type ColorStep = keyof (typeof palette)['teal']

export type ThemeName = 'light' | 'dark'

/**
 * Chart colours, resolved per theme.
 *
 * Charts are the one place a JavaScript colour value is genuinely required: a canvas renderer or
 * an SVG attribute needs a string, and reading CSS variables back with `getComputedStyle` on
 * every render is slow and returns nothing during SSR.
 *
 * Everything else must use the CSS variables.
 */
export const chartColors = {
  light: {
  'chart-1': '#4d78ca',
  'chart-2': '#cf6951',
  'chart-3': '#2f904d',
  'chart-4': '#9f73cb',
  'chart-5': '#a17000',
  'chart-6': '#2294d3',
  'chart-7': '#b35585',
  'chart-8': '#7d972b',
  'chart-9': '#726dc7',
  'chart-10': '#c7722b',
  'chart-11': '#a45aa2',
  'chart-12': '#ce6475',
  'chart-positive': '#218548',
  'chart-negative': '#bd3e37',
  'chart-neutral': '#7e929d',
  'chart-baseline': '#a2b4be',
  'chart-target': '#008180',
  'chart-reference': '#c6d4dc',
  'chart-forecast': '#13a3a280',
  'chart-missing': '#dee6ec',
  'chart-grid': '#a2b4be2e',
  'chart-axis': '#a2b4be',
} as const,
  dark: {
  'chart-1': '#81a9f2',
  'chart-2': '#d57d68',
  'chart-3': '#71be82',
  'chart-4': '#aa85d0',
  'chart-5': '#d1a04e',
  'chart-6': '#4da1d8',
  'chart-7': '#e08ab3',
  'chart-8': '#8ca34e',
  'chart-9': '#a09fef',
  'chart-10': '#ce844e',
  'chart-11': '#d18fce',
  'chart-12': '#d57985',
  'chart-positive': '#75c68c',
  'chart-negative': '#ff8a7e',
  'chart-neutral': '#7e929d',
  'chart-baseline': '#61737e',
  'chart-target': '#5ec4c2',
  'chart-reference': '#4a5f6b',
  'chart-forecast': '#5ec4c280',
  'chart-missing': '#354c59',
  'chart-grid': '#a2b4be1f',
  'chart-axis': '#61737e',
} as const,
}

/** The twelve categorical series, in order, for the given theme. */
export const chartSeries = (theme: ThemeName): readonly string[] =>
  Array.from({ length: 12 }, (_, i) => chartColors[theme][`chart-${i + 1}` as 'chart-1'])

/**
 * Stable modality → chart slot mapping.
 *
 * A CONVENTION so a modality keeps its colour across every chart in the product, not a semantic
 * claim. Strength is not red because strength is dangerous; it is slot 1 because something had
 * to be. See the reasoning in tools/color/semantic.mjs.
 */
export const modalityChartSlot = {
  'strength': '1',
  'endurance': '2',
  'mobility': '3',
  'recovery': '4',
  'load': '5',
  'fatigue': '6',
} as const

export type Modality = keyof typeof modalityChartSlot

export const modalityColor = (modality: Modality, theme: ThemeName): string =>
  chartColors[theme][`chart-${modalityChartSlot[modality]}` as 'chart-1']

/** Semantic token names, for tooling that needs to enumerate them. */
export const semanticTokenNames = [
  "bg-canvas",
  "bg-surface",
  "bg-surface-subtle",
  "bg-surface-elevated",
  "bg-surface-hover",
  "bg-surface-active",
  "bg-surface-sunken",
  "bg-inverse",
  "text-primary",
  "text-secondary",
  "text-muted",
  "text-disabled",
  "text-inverse",
  "text-brand",
  "text-on-brand",
  "border-subtle",
  "border-default",
  "border-strong",
  "border-brand",
  "action-primary",
  "action-primary-hover",
  "action-primary-active",
  "action-primary-fg",
  "action-secondary",
  "action-secondary-hover",
  "action-secondary-active",
  "action-secondary-fg",
  "action-ghost-hover",
  "action-ghost-active",
  "action-ghost-fg",
  "action-destructive",
  "action-destructive-hover",
  "action-destructive-active",
  "action-destructive-fg",
  "action-disabled",
  "action-disabled-fg",
  "status-success-surface",
  "status-success-border",
  "status-success-fg",
  "status-success-solid",
  "status-warning-surface",
  "status-warning-border",
  "status-warning-fg",
  "status-warning-solid",
  "status-error-surface",
  "status-error-border",
  "status-error-fg",
  "status-error-solid",
  "status-info-surface",
  "status-info-border",
  "status-info-fg",
  "status-info-solid",
  "focus",
  "focus-offset",
  "selection-bg",
  "selection-fg",
  "overlay",
  "scrim"
] as const
