/**
 * @fitnessos/editor-engine — the document, history and geometry engine behind every builder.
 *
 * Framework-free by rule (`no-react-in-logic`): no React, no DOM, no rendering. It owns the
 * document, the actions, undo/redo and spatial queries; a builder owns presentation and wires the
 * two together. React Flow, when the Workflow Builder needs it, owns rendering only and is never
 * the source of truth (D-11).
 *
 * What is here: D-01 history, D-02 flat document, D-03 spatial index, D-04 coordinate spaces,
 * D-08 cross-document references, and the spatial topology the Report Builder needs — hit
 * testing, snapping and alignment. All three were ADDITIVE: Phase 4's exit gate asks that the
 * Report Builder change nothing existing, and it changed nothing existing.
 *
 * What is not: nested sub-documents (D-07). Not an oversight — nothing in the product has a
 * nested document yet. A programme's blocks contain no sub-structure the coach authors; the
 * `PrescribedSession` items an athlete follows are generated by the backend from the programme
 * (ADR-0013), not typed into it. The first real D-07 consumer will be the Report or Form builder,
 * and designing the modal-with-throwaway-history against no consumer is how an API acquires the
 * wrong shape and then five builders inherit it.
 */

export {
  childrenOf,
  descendantsOf,
  emptyDocument,
  nodeAt,
  parentOf,
  walk,
  type DocumentSnapshot,
  type Node,
  type NodeId,
} from './document/snapshot'

export {
  applyAction,
  invertAction,
  isStructural,
  targetsOf,
  type EditorAction,
  type InsertNode,
  type InsertSubtree,
  type MoveNodes,
  type NodePosition,
  type RemoveNode,
  type RestorePositions,
  type SetProperty,
} from './document/actions'

export {
  DEFAULT_HISTORY_CONFIG,
  canRedo,
  canUndo,
  commitBoundary,
  createHistory,
  push,
  pushBatch,
  redo,
  undo,
  type HistoryConfig,
  type HistoryEntry,
  type HistoryState,
  type PushOptions,
} from './history/history'

export {
  clientPoint,
  documentPoint,
  documentRect,
  fromClient,
  rectContains,
  rectToScreen,
  rectsOverlap,
  screenPixels,
  screenPoint,
  thresholdInDocument,
  toDocument,
  toScreen,
  type ClientPoint,
  type DocumentPoint,
  type DocumentRect,
  type ScreenPixels,
  type ScreenPoint,
  type ScreenRect,
  type Viewport,
} from './geometry/spaces'

export { SpatialHash } from './geometry/spatialHash'

export { hitPoint, hitRect } from './geometry/hitTest'

export {
  applySnap,
  snap,
  type GuideLine,
  type SnapConfig,
  type SnapResult,
} from './geometry/snapping'

export {
  clampToGrid,
  compactGrid,
  resolveCollisions,
  type GridItem,
} from './geometry/grid'

export {
  align,
  distribute,
  type Alignment,
  type Positioned,
} from './geometry/alignment'

export {
  isDocumentRef,
  refKey,
  refsIn,
  remapIds,
  type BrokenRef,
  type DocumentRef,
  type RefKind,
  type RefResolution,
  type ReferenceResolver,
  type ResolvedRef,
} from './references/refs'
