/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/athletes/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The calling person's athlete record */
        get: operations["getMyAthlete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and reissue the access cookie
         * @description Strict rotation: the presented token is revoked. Concurrent callers MUST be serialised client-side or they will revoke each other's freshly issued session.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @description stable machine-readable code */
            code: string;
            detail: string;
        };
        Athlete: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            status: "active" | "dormant" | "archived";
            trainingIdentity: components["schemas"]["TrainingIdentity"];
            availability: components["schemas"]["Availability"];
        };
        TrainingIdentity: {
            trainingAgeMonths?: number;
            /** @enum {string} */
            experienceLevel: "beginner" | "intermediate" | "advanced";
            disciplines: string[];
        };
        Availability: {
            daysPerWeek: number;
            /** @description Duration in seconds. Unit is explicit in the name because N11 forbids an ambiguous magnitude. */
            sessionCeilingSeconds?: number;
            equipmentAccess: string[];
        };
    };
    responses: {
        /** @description no valid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyAthlete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Athlete"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cookies reissued */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
