/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/athletes/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The calling person's athlete record */
        get: operations["getMyAthlete"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and reissue the access cookie
         * @description Strict rotation: the presented token is revoked. Concurrent callers MUST be serialised client-side or they will revoke each other's freshly issued session.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a one-time code by SMS
         * @description Rate limited per IP and per phone. Returns the same shape whether or not the phone is registered — a differing response would make this an account-enumeration oracle.
         */
        post: operations["requestCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a one-time code for a session
         * @description On success sets the access and refresh cookies (httpOnly, SameSite=Lax). No token is ever returned in the body — a token readable from JS is a token exfiltrable by XSS.
         */
        post: operations["verifyCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/athletes/me/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record the athlete's training identity and availability
         * @description PUT rather than POST: submitting the same body twice must leave the athlete in the same state. Onboarding is a form a user will resubmit after a network hiccup, and an idempotent verb is what makes that safe without a client-generated request id.
         */
        put: operations["completeOnboarding"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The calling athlete's goals */
        get: operations["listMyGoals"];
        put?: never;
        /**
         * Declare a goal
         * @description POST rather than PUT: declaring a goal creates a new one each time, and two goals with the same wording are legitimately different goals declared at different moments.
         */
        post: operations["declareGoal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            /** @description stable machine-readable code */
            code: string;
            detail: string;
        };
        Athlete: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            personId: string;
            /** @enum {string} */
            status: "active" | "dormant" | "archived";
            trainingIdentity: components["schemas"]["TrainingIdentity"];
            availability: components["schemas"]["Availability"];
        };
        TrainingIdentity: {
            trainingAgeMonths?: number;
            /** @enum {string} */
            experienceLevel: "beginner" | "intermediate" | "advanced";
            disciplines: string[];
        };
        Availability: {
            daysPerWeek: number;
            /** @description Duration in seconds. Unit is explicit in the name because N11 forbids an ambiguous magnitude. */
            sessionCeilingSeconds?: number;
            equipmentAccess: string[];
        };
        RequestCodeBody: {
            /** @description E.164. The client normalises Persian/Arabic-Indic digits and local prefixes before sending; the server receives one canonical form only. */
            phone: string;
        };
        RequestCodeResult: {
            /** @description Seconds until another code may be requested. Unit is explicit in the name because N11 forbids an ambiguous magnitude. Server-authoritative: the client must not compute its own cooldown. */
            retryAfterSeconds: number;
            /** @description So the client does not hardcode a length the server can change. */
            codeLength: number;
        };
        VerifyCodeBody: {
            phone: string;
            code: string;
        };
        VerifyCodeResult: {
            /** Format: uuid */
            personId: string;
            /** @description True when this verification created the person. The client routes to onboarding rather than the dashboard. */
            isNewPerson: boolean;
        };
        CompleteOnboardingBody: {
            trainingIdentity: components["schemas"]["TrainingIdentity"];
            availability: components["schemas"]["Availability"];
        };
        Goal: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            athleteId: string;
            /** @description The athlete's own words, verbatim. Never a normalised or translated form -- losing the phrasing is not recoverable. */
            intent: string;
            /**
             * Format: date
             * @description ISO date, no time. The declaration is a calendar fact in the athlete's zone.
             */
            declaredOn: string;
            /**
             * Format: date
             * @description Absent means open-ended, which is a valid answer.
             */
            horizon?: string;
            /** @description Evaluation cadence. NOT a status: staleness and expiry are derived from this plus a date (ADR-0006), never stored. */
            cadenceDays: number;
        };
        DeclareGoalBody: {
            intent: string;
            /** Format: date */
            horizon?: string;
            cadenceDays: number;
        };
    };
    responses: {
        /** @description no valid session */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getMyAthlete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Athlete"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description cookies reissued */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestCodeBody"];
            };
        };
        responses: {
            /** @description code dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestCodeResult"];
                };
            };
            /** @description rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    verifyCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyCodeBody"];
            };
        };
        responses: {
            /** @description session established */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyCodeResult"];
                };
            };
            /** @description code incorrect or expired */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description too many attempts */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    completeOnboarding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteOnboardingBody"];
            };
        };
        responses: {
            /** @description recorded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Athlete"];
                };
            };
            /** @description invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listMyGoals: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    declareGoal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeclareGoalBody"];
            };
        };
        responses: {
            /** @description declared */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Goal"];
                };
            };
            /** @description invalid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
}
