/* eslint-disable */
/**
 * GENERATED by scripts/generate-schemas.mjs from spec/openapi.json. Do not hand-edit.
 *
 * Runtime validators for response bodies (ADR-0031). The compile-time types in
 * api.gen.ts come from the same spec, so the two cannot describe different shapes.
 *
 * Deliberately NOT `.strict()`: unknown keys are stripped rather than rejected, so
 * a backend adding a field cannot break the frontend. Missing required fields and
 * wrong types still fail, which is the set of changes that would otherwise corrupt
 * data silently.
 */
import { z } from 'zod'

export const ProblemSchema = z.object({ "code": z.string().describe("stable machine-readable code"), "detail": z.string() })

export const TrainingIdentitySchema = z.object({ "trainingAgeMonths": z.number().int().gte(0).optional(), "experienceLevel": z.enum(["beginner","intermediate","advanced"]), "disciplines": z.array(z.string()) })

export const AvailabilitySchema = z.object({ "daysPerWeek": z.number().int().gte(1).lte(7), "sessionCeilingSeconds": z.number().int().gte(600).describe("Duration in seconds. Unit is explicit in the name because N11 forbids an ambiguous magnitude.").optional(), "equipmentAccess": z.array(z.string()) })

export const AthleteSchema = z.object({ "id": z.string().uuid(), "personId": z.string().uuid(), "status": z.enum(["active","dormant","archived"]), "trainingIdentity": TrainingIdentitySchema, "availability": AvailabilitySchema })

export const RequestCodeBodySchema = z.object({ "phone": z.string().regex(new RegExp("^\\+989[0-9]{9}$")).describe("E.164. The client normalises Persian/Arabic-Indic digits and local prefixes before sending; the server receives one canonical form only.") })

export const RequestCodeResultSchema = z.object({ "retryAfterSeconds": z.number().int().gte(0).describe("Seconds until another code may be requested. Unit is explicit in the name because N11 forbids an ambiguous magnitude. Server-authoritative: the client must not compute its own cooldown."), "codeLength": z.number().int().gte(4).lte(8).describe("So the client does not hardcode a length the server can change.") })

export const VerifyCodeBodySchema = z.object({ "phone": z.string().regex(new RegExp("^\\+989[0-9]{9}$")), "code": z.string().regex(new RegExp("^[0-9]{4,8}$")) })

export const VerifyCodeResultSchema = z.object({ "personId": z.string().uuid(), "isNewPerson": z.boolean().describe("True when this verification created the person. The client routes to onboarding rather than the dashboard.") })

export const CompleteOnboardingBodySchema = z.object({ "trainingIdentity": TrainingIdentitySchema, "availability": AvailabilitySchema })

export const GoalSchema = z.object({ "id": z.string().uuid(), "athleteId": z.string().uuid(), "intent": z.string().min(1).max(200).describe("The athlete's own words, verbatim. Never a normalised or translated form -- losing the phrasing is not recoverable."), "declaredOn": z.string().date().describe("ISO date, no time. The declaration is a calendar fact in the athlete's zone."), "horizon": z.string().date().describe("Absent means open-ended, which is a valid answer.").optional(), "cadenceDays": z.number().int().gte(7).lte(365).describe("Evaluation cadence. NOT a status: staleness and expiry are derived from this plus a date (ADR-0006), never stored.") })

export const DeclareGoalBodySchema = z.object({ "intent": z.string().min(1).max(200), "horizon": z.string().date().optional(), "cadenceDays": z.number().int().gte(7).lte(365) })

export const ProgressionIntentSchema = z.object({ "kind": z.enum(["fixed","linear","autoregulated"]), "ratePercent": z.number().gt(0).lte(20).describe("Percent per cycle. Present only for kind=linear. Percent rather than absolute because the same increment is trivial for one athlete and impossible for another.").optional() })

export const BlockSchema = z.object({ "id": z.string().uuid(), "name": z.string().min(1), "order": z.number().int().gte(0).describe("Zero-based. Orders across a version must be exactly 0..n-1, each once."), "progressionIntent": ProgressionIntentSchema })

export const ServesGoalSchema = z.object({ "goalId": z.string().uuid(), "rationale": z.string().optional() }).describe("States current purpose. NEVER an input to outcome evaluation (ADR-0008).")

export const AuthoringDecisionSchema = z.object({ "decidedBy": z.string(), "proposedBy": z.enum(["human","assistant"]).describe("Separate from decidedBy: an AI-proposed programme accepted by a coach was DECIDED by the coach. Collapsing them loses the fact that makes ADR-0003 auditable."), "rationale": z.string().optional() })

export const ProgramVersionSchema = z.object({ "id": z.string().uuid(), "programId": z.string().uuid(), "versionNumber": z.number().int().gte(1), "blocks": z.array(BlockSchema).min(1), "servesGoal": ServesGoalSchema.optional(), "authoringDecision": AuthoringDecisionSchema })

export const ProgramSchema = z.object({ "id": z.string().uuid(), "athleteId": z.string().uuid(), "title": z.string().min(1), "currentVersion": ProgramVersionSchema }).describe("The LINEAGE plus its current structure. Program and ProgramVersion are separate aggregates (ADR-0008); this envelope is a read projection, not a merge.")

export const ScreeningVerdictSchema = z.object({ "level": z.enum(["clear","modified","blocked"]), "basis": z.string().describe("Why. Absent when consent-gated (ADR-0002/0014), which is NOT the same as absent because there is no reason -- see basisWithheld.").optional(), "basisWithheld": z.boolean().describe("True when a basis exists but this viewer may not see it. Distinguishes the two reasons basis can be absent.") })

export const PrescribedItemSchema = z.object({ "id": z.string().uuid(), "movementName": z.string().min(1), "order": z.number().int().gte(0), "sets": z.number().int().gte(1), "reps": z.number().int().gte(1), "loadKg": z.number().gt(0).describe("Resolved load in kilograms. ABSENT for bodyweight or time-based work -- never 0, which is what an unresolved progression writes.").optional() })

export const PrescribedSessionSchema = z.object({ "id": z.string().uuid(), "programVersionId": z.string().uuid(), "scheduledFor": z.string().date(), "items": z.array(PrescribedItemSchema).min(1), "screening": ScreeningVerdictSchema }).describe("Required screening is ADR-0021: a PrescribedSession cannot exist without a verdict covering its final RESOLVED dose. Screening an intent is worthless -- an intent has no numbers to screen.")

export const PerformedSetSchema = z.object({ "id": z.string().uuid(), "prescribedItemId": z.string().uuid(), "setNumber": z.number().int().gte(1), "reps": z.number().int().gte(1), "loadKg": z.number().gt(0).describe("Absent for bodyweight. Never 0.").optional(), "rpe": z.number().multipleOf(0.5).gte(1).lte(10).optional() })

export const LogSessionBodySchema = z.object({ "id": z.string().uuid().describe("CLIENT-generated UUIDv7 (D-10). The idempotency key: a queued log replayed after a lost response arrives with the same id, and the server MUST answer 409 rather than creating a second record. Offline replay is at-least-once and this is what makes it safe."), "prescribedSessionId": z.string().uuid(), "performedOn": z.string().date().describe("Independent of the prescription's scheduledFor. Monday's session may be performed on Tuesday."), "sets": z.array(PerformedSetSchema).min(1), "note": z.string().max(500).optional() })

export const PerformedSessionSchema = z.object({ "id": z.string().uuid(), "prescribedSessionId": z.string().uuid(), "performedOn": z.string().date(), "sets": z.array(PerformedSetSchema).min(1), "note": z.string().optional() })

export const ReviseProgramBodySchema = z.object({ "id": z.string().uuid().describe("CLIENT-generated id for the NEW version (D-10). The idempotency key: a revision replayed after a lost response arrives with the same id, and the server MUST return the stored version with 200 rather than creating a second one. Without it, a coach who loses the response and retries silently creates two versions and the athlete's programme jumps two numbers."), "baseVersionId": z.string().uuid().describe("The version this revision was edited FROM. If it is no longer current, another author revised in the meantime and the server MUST answer 409 with the version that is current now -- overwriting would discard their work with no trace. Optimistic concurrency rather than locking, because a coach with a builder open for an hour must not hold a lock for an hour."), "blocks": z.array(BlockSchema).min(1), "servesGoal": ServesGoalSchema.optional(), "authoringDecision": AuthoringDecisionSchema }).describe("A revision creates a NEW version and leaves the old one untouched (ADR-0008): a structure an athlete has already followed cannot be edited without making every PerformedSession against it unreadable. versionNumber is assigned by the server, not sent -- it is derived from the lineage and a client that guessed it would race another author.")
