/* eslint-disable */
/**
 * GENERATED by scripts/generate-schemas.mjs from spec/openapi.json. Do not hand-edit.
 *
 * Runtime validators for response bodies (ADR-0031). The compile-time types in
 * api.gen.ts come from the same spec, so the two cannot describe different shapes.
 *
 * Deliberately NOT `.strict()`: unknown keys are stripped rather than rejected, so
 * a backend adding a field cannot break the frontend. Missing required fields and
 * wrong types still fail, which is the set of changes that would otherwise corrupt
 * data silently.
 */
import { z } from 'zod'

export const ProblemSchema = z.object({ "code": z.string().describe("stable machine-readable code"), "detail": z.string() })

export const TrainingIdentitySchema = z.object({ "trainingAgeMonths": z.number().int().gte(0).optional(), "experienceLevel": z.enum(["beginner","intermediate","advanced"]), "disciplines": z.array(z.string()) })

export const AvailabilitySchema = z.object({ "daysPerWeek": z.number().int().gte(1).lte(7), "sessionCeilingSeconds": z.number().int().gte(600).describe("Duration in seconds. Unit is explicit in the name because N11 forbids an ambiguous magnitude.").optional(), "equipmentAccess": z.array(z.string()) })

export const AthleteSchema = z.object({ "id": z.string().uuid(), "personId": z.string().uuid(), "status": z.enum(["active","dormant","archived"]), "trainingIdentity": TrainingIdentitySchema, "availability": AvailabilitySchema })

export const RequestCodeBodySchema = z.object({ "phone": z.string().regex(new RegExp("^\\+989[0-9]{9}$")).describe("E.164. The client normalises Persian/Arabic-Indic digits and local prefixes before sending; the server receives one canonical form only.") })

export const RequestCodeResultSchema = z.object({ "retryAfterSeconds": z.number().int().gte(0).describe("Seconds until another code may be requested. Unit is explicit in the name because N11 forbids an ambiguous magnitude. Server-authoritative: the client must not compute its own cooldown."), "codeLength": z.number().int().gte(4).lte(8).describe("So the client does not hardcode a length the server can change.") })

export const VerifyCodeBodySchema = z.object({ "phone": z.string().regex(new RegExp("^\\+989[0-9]{9}$")), "code": z.string().regex(new RegExp("^[0-9]{4,8}$")) })

export const VerifyCodeResultSchema = z.object({ "personId": z.string().uuid(), "isNewPerson": z.boolean().describe("True when this verification created the person. The client routes to onboarding rather than the dashboard.") })
