import { err, ok, type GoalId, type PlainDate, type Result } from '@fitnessos/kernel'
import { MIN_PHASE_DAYS, spansOverlap, type Span } from '../topology/temporal'

/**
 * `Plan` — a periodisation, laid out on time.
 *
 * A coach's statement of intent over months: an accumulation phase, then intensification, then a
 * taper. Each phase is a SPAN with a stated purpose, and nothing else.
 *
 * ## What this deliberately is not
 *
 * It is not a schedule of sessions — those are `PrescribedSession`, generated by the backend from
 * a programme (ADR-0013), and a plan that listed them would be holding another context's model.
 *
 * It is not a `ProgramVersion` either, and the distinction is the one ADR-0008 already draws for
 * a different reason: a programme says WHAT the training is — blocks, progression intents — with
 * no dates at all. A plan says WHEN, and says nothing about content. A coach can reschedule a
 * taper without revising a single block, and can rewrite a block without moving a date. Two
 * facts, two aggregates.
 *
 * A phase may name the programme it intends to run, by id and nothing more, so this context
 * never reads Prescription's model.
 */

const brand = Symbol('Plan')

export interface Phase {
  readonly id: string
  /** The coach's name for it — "accumulation", "peak". Their words, not a fixed vocabulary. */
  readonly label: string
  /** Day offsets from the plan's epoch, in whole days. See `topology/temporal`. */
  readonly start: number
  readonly length: number
  /** Opaque. This context never dereferences it. */
  readonly programId: string | null
  /** What the phase is for. Never an evaluation input (ADR-0008). */
  readonly servesGoal: GoalId | null
}

export interface Plan {
  readonly [brand]: true
  readonly id: string
  readonly title: string
  /** Day zero. Every phase offset is relative to this, so the plan can be shifted wholesale. */
  readonly epoch: PlainDate
  readonly phases: readonly Phase[]
}

export type PlanError =
  | { readonly kind: 'title-empty' }
  | { readonly kind: 'duplicate-phase-id'; readonly id: string }
  | { readonly kind: 'label-empty'; readonly id: string }
  | { readonly kind: 'phase-starts-before-epoch'; readonly id: string }
  | { readonly kind: 'phase-too-short'; readonly id: string; readonly min: number }
  | { readonly kind: 'phase-length-not-whole'; readonly id: string }
  | { readonly kind: 'phases-overlap'; readonly a: string; readonly b: string }

export interface PlanInput {
  readonly id: string
  readonly title: string
  readonly epoch: PlainDate
  readonly phases: readonly Phase[]
}

export const plan = (input: PlanInput): Result<Plan, PlanError> => {
  if (input.title.trim() === '') return err({ kind: 'title-empty' })

  const seen = new Set<string>()
  for (const phase of input.phases) {
    if (seen.has(phase.id)) return err({ kind: 'duplicate-phase-id', id: phase.id })
    seen.add(phase.id)

    if (phase.label.trim() === '') return err({ kind: 'label-empty', id: phase.id })
    if (!Number.isInteger(phase.start) || !Number.isInteger(phase.length)) {
      // Half a day is not something a plan can express, and a fraction here is a conversion that
      // went through `Date` when it should have gone through `addDays`.
      return err({ kind: 'phase-length-not-whole', id: phase.id })
    }
    if (phase.start < 0) return err({ kind: 'phase-starts-before-epoch', id: phase.id })
    if (phase.length < MIN_PHASE_DAYS) {
      return err({ kind: 'phase-too-short', id: phase.id, min: MIN_PHASE_DAYS })
    }
  }

  /*
   * Phases may not overlap, and unlike a grid there is nowhere to push one to.
   *
   * An athlete is in one phase at a time. Two overlapping phases do not render oddly — they make
   * "what am I doing this week" unanswerable, which is the only question the plan exists to
   * answer.
   */
  for (const [i, a] of input.phases.entries()) {
    for (const b of input.phases.slice(i + 1)) {
      const spanA: Span = { start: a.start, length: a.length }
      const spanB: Span = { start: b.start, length: b.length }
      if (spansOverlap(spanA, spanB)) return err({ kind: 'phases-overlap', a: a.id, b: b.id })
    }
  }

  return ok({
    [brand]: true,
    id: input.id,
    title: input.title.trim(),
    epoch: input.epoch,
    // Sorted by start, because time HAS an order — unlike a grid, where position carries it all.
    // A plan read out of sequence is not a plan.
    phases: [...input.phases].sort((a, b) => a.start - b.start),
  })
}

/** Whether a plan covers a day at all, and which phase does. Derived, never stored (ADR-0006). */
export const phaseOn = (subject: Plan, offset: number): Phase | null =>
  subject.phases.find((phase) => offset >= phase.start && offset < phase.start + phase.length) ??
  null
