#!/usr/bin/env node
/**
 * Emits the design-token package from the palette definition.
 *
 * Two outputs, because two consumers need different things:
 *
 *   `tokens.css`      CSS custom properties. What components use, via Tailwind utilities.
 *   `generated.ts`    the same values as TypeScript. What CHARTS use — a charting library needs
 *                     a colour string to pass to a canvas or an SVG attribute, and reading a CSS
 *                     variable back out via `getComputedStyle` on every render is both slow and
 *                     unavailable during SSR.
 *
 * Both are generated from one source, so they cannot disagree. Committed rather than built at
 * install time, so a reviewer sees the colour change in the diff that caused it.
 */
import { writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { PALETTE, STEPS } from './palette.mjs'
import { CHART_TOKENS, DARK, DOMAIN, EDITOR, LIGHT, MODALITY_CHART_SLOT } from './semantic.mjs'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..')
const out = resolve(root, 'packages/design-tokens/src')
mkdirSync(out, { recursive: true })

const BANNER = `/* GENERATED by tools/color/emit.mjs. Do not hand-edit.
 *
 * Change a colour in tools/color/palette.mjs or semantic.mjs, run \`pnpm tokens:build\`, and
 * commit the result. \`pnpm tokens:check\` fails CI if these files are stale, and
 * \`pnpm color:contrast\` fails it if any pair drops below its WCAG threshold.
 */`

// --- CSS -------------------------------------------------------------------
const block = (tokens, indent = '  ') =>
  Object.entries(tokens)
    .map(([name, value]) => `${indent}--${name}: ${value};`)
    .join('\n')

const primitives = Object.entries(PALETTE)
  .map(([family, scale]) =>
    STEPS.map((step) => `  --color-${family}-${step}: ${scale[step].hex};`).join('\n'),
  )
  .join('\n\n')

const css = `${BANNER}

/* ==========================================================================
   LEVEL 1 — PRIMITIVES
   Raw palette. A component must never reference these directly; they exist so the
   semantic layer below has something to point at, and so a future theme can repoint it.
   ========================================================================== */
:root {
${primitives}
}

/* ==========================================================================
   LEVEL 2 — SEMANTIC (light)
   What components use. Every value here is a role, not a colour.
   ========================================================================== */
:root,
[data-theme='light'] {
  color-scheme: light;

${block(LIGHT)}

${block(CHART_TOKENS.light)}

${block(EDITOR.light)}

${block(DOMAIN.light)}
}

/* ==========================================================================
   LEVEL 2 — SEMANTIC (dark)
   Designed, not inverted. See the note in tools/color/semantic.mjs.
   ========================================================================== */
[data-theme='dark'] {
  color-scheme: dark;

${block(DARK)}

${block(CHART_TOKENS.dark)}

${block(EDITOR.dark)}

${block(DOMAIN.dark)}
}

/* Respect the OS preference when the app has not stored an explicit choice.
   The [data-theme] attribute always wins, so a user's toggle overrides the system. */
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
    color-scheme: dark;

${block(DARK, '    ')}

${block(CHART_TOKENS.dark, '    ')}

${block(EDITOR.dark, '    ')}

${block(DOMAIN.dark, '    ')}
  }
}
`

/*
 * shadcn/ui compatibility.
 *
 * shadcn components are copied INTO the repo and reference a fixed set of variable names. Rather
 * than editing each component after every `shadcn add` — which loses the ability to re-run the
 * generator — those names are aliased onto our semantic tokens here. A component pasted from the
 * shadcn CLI then works with no edit at all.
 *
 * Two mappings are deliberate departures from the shadcn defaults:
 *
 *   --input   → border-STRONG, not border-default. shadcn uses `--input` for a field's outline,
 *              which is an interactive boundary and needs 3:1 (WCAG 1.4.11). border-default is a
 *              decorative divider and measures 1.5:1. Using it would ship inaccessible inputs on
 *              every shadcn form in the product.
 *
 *   --background → the CANVAS, and --card → the surface. shadcn conflates them; we do not,
 *              because cards being white on an off-white canvas is what removes the need for
 *              card borders.
 */
const shadcn = `
/* ==========================================================================
   shadcn/ui compatibility aliases
   These map shadcn's fixed variable names onto our semantic tokens, so a component
   copied from the shadcn CLI works unmodified. Do not use these names in our own
   components — use the semantic tokens directly.
   ========================================================================== */
:root,
[data-theme='light'],
[data-theme='dark'] {
  --background: var(--bg-canvas);
  --foreground: var(--text-primary);
  --card: var(--bg-surface);
  --card-foreground: var(--text-primary);
  --popover: var(--bg-surface-elevated);
  --popover-foreground: var(--text-primary);
  --primary: var(--action-primary);
  --primary-foreground: var(--action-primary-fg);
  --secondary: var(--action-secondary);
  --secondary-foreground: var(--action-secondary-fg);
  --muted: var(--bg-surface-subtle);
  --muted-foreground: var(--text-muted);
  --accent: var(--bg-surface-hover);
  --accent-foreground: var(--text-primary);
  --destructive: var(--action-destructive);
  --destructive-foreground: var(--action-destructive-fg);
  --border: var(--border-default);
  --input: var(--border-strong);
  --ring: var(--focus);

  /* FitnessOS additions. shadcn has no equivalent, and a product this size needs them. */
  --success: var(--status-success-solid);
  --success-foreground: var(--status-success-fg);
  --warning: var(--status-warning-solid);
  --warning-foreground: var(--status-warning-fg);
  --info: var(--status-info-solid);
  --info-foreground: var(--status-info-fg);
  --surface-elevated: var(--bg-surface-elevated);
  --surface-hover: var(--bg-surface-hover);
  --overlay: var(--overlay);
}
`

writeFileSync(resolve(out, 'tokens.css'), css + shadcn)

// --- TypeScript ------------------------------------------------------------
const tsRecord = (obj) =>
  `{\n${Object.entries(obj)
    .map(([k, v]) => `  '${k}': '${v}',`)
    .join('\n')}\n}`

const ts = `${BANNER}

/**
 * Palette primitives. Exported for tooling and tests — NOT for components, which must use the
 * semantic CSS variables so a theme change reaches them.
 */
export const palette = {
${Object.entries(PALETTE)
  .map(
    ([family, scale]) =>
      `  ${family}: {\n${STEPS.map((s) => `    ${s}: '${scale[s].hex}',`).join('\n')}\n  },`,
  )
  .join('\n')}
} as const

export type ColorFamily = keyof typeof palette
export type ColorStep = keyof (typeof palette)['teal']

export type ThemeName = 'light' | 'dark'

/**
 * Chart colours, resolved per theme.
 *
 * Charts are the one place a JavaScript colour value is genuinely required: a canvas renderer or
 * an SVG attribute needs a string, and reading CSS variables back with \`getComputedStyle\` on
 * every render is slow and returns nothing during SSR.
 *
 * Everything else must use the CSS variables.
 */
export const chartColors = {
  light: ${tsRecord(CHART_TOKENS.light)} as const,
  dark: ${tsRecord(CHART_TOKENS.dark)} as const,
}

/** The twelve categorical series, in order, for the given theme. */
export const chartSeries = (theme: ThemeName): readonly string[] =>
  Array.from({ length: 12 }, (_, i) => chartColors[theme][\`chart-\${i + 1}\` as 'chart-1'])

/**
 * Stable modality → chart slot mapping.
 *
 * A CONVENTION so a modality keeps its colour across every chart in the product, not a semantic
 * claim. Strength is not red because strength is dangerous; it is slot 1 because something had
 * to be. See the reasoning in tools/color/semantic.mjs.
 */
export const modalityChartSlot = ${tsRecord(MODALITY_CHART_SLOT)} as const

export type Modality = keyof typeof modalityChartSlot

export const modalityColor = (modality: Modality, theme: ThemeName): string =>
  chartColors[theme][\`chart-\${modalityChartSlot[modality]}\` as 'chart-1']

/** Semantic token names, for tooling that needs to enumerate them. */
export const semanticTokenNames = ${JSON.stringify(Object.keys(LIGHT), null, 2)} as const
`

writeFileSync(resolve(out, 'generated.ts'), ts)

console.log(`✔ tokens written`)
console.log(`    packages/design-tokens/src/tokens.css     ${Object.keys(LIGHT).length} semantic · ${Object.keys(CHART_TOKENS.light).length} chart · ${Object.keys(EDITOR.light).length} editor · ${Object.keys(DOMAIN.light).length} domain`)
console.log(`    packages/design-tokens/src/generated.ts`)
